Gita
fitristachan/proyek-magang pull request #3
Opened 2023-07-16 19:09 UTC by fitristachan

2023-07-16 19:17 UTC, fitristachan commented
plis bantu merge, takut gua. makasii sebelumnya.

2023-07-17 02:24 UTC, rianfrhn commented on app/Config/Routes.php
> +
tambahin
$routes->get("/spk/", "SPK::index");
$routes->post('/spk/submit', 'SPK::submit_alternative');
$routes->get('/nextpage', 'SPK::index');
$routes->get('/spk/result/(:num)', 'SPK::result/$1');

2023-07-17 02:26 UTC, rianfrhn commented on app/Config/Database.php
keknya jangan setup databasenya disini. Pake .env aja

2023-07-17 02:27 UTC, rianfrhn requested changes
route tambahin:
$routes->get("/spk/", "SPK::index");
$routes->post('/spk/submit', 'SPK::submit_alternative');
$routes->get('/nextpage', 'SPK::index');
$routes->get('/spk/result/(:num)', 'SPK::result/$1');

Database jg keknya pake .env aja biar ga ribet setting" ulang tiap kali merge

2023-07-17 02:30 UTC, fitristachan commented on app/Config/Routes.php
> +$routes->get("/spk/", "SPK::index");
@rianfrhn iniii

2023-07-17 02:31 UTC, rianfrhn commented on app/Config/Routes.php
> +$routes->get("/spk/", "SPK::index");
ow iya

2023-07-17 02:39 UTC, rianfrhn approved these changes

2023-07-17 02:39 UTC, merged